[2020-06-15 11:41:42] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 20, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\envbin\py37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Sound is not JSON serializable
[2020-06-15 12:09:39] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 20, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\envbin\py37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Sound is not JSON serializable
[2020-06-15 12:24:11] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 20, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'Particle' and 'Particle'
[2020-06-15 12:25:47] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 20, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'Particle' and 'Particle'
[2020-06-15 12:26:21] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 21, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'Particle' and 'Particle'
[2020-06-15 12:32:04] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 21, in environment_data
    return jsonify(DEFAULT_DATA['fs2s'])
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: '<' not supported between instances of 'Particle' and 'Particle'
[2020-06-15 12:37:02] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 21, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\__init__.py", line 23, in default
    return super(PhonogenesisJSONEncoder, self).default(o)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\envbin\py37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type GlossFamily is not JSON serializable
[2020-06-15 12:38:32] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 21, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\__init__.py", line 23, in default
    return super(PhonogenesisJSONEncoder, self).default(o)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\envbin\py37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type GlossFamily is not JSON serializable
[2020-06-15 12:39:10] - ERROR - Exception on /env [GET] - app 1892@log_exception
Traceback (most recent call last):
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\routes.py", line 21, in environment_data
    return jsonify(DEFAULT_DATA)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\envbin\py37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\envbin\py37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\envbin\py37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\app\__init__.py", line 23, in default
    return super(PhonogenesisJSONEncoder, self).default(o)
  File "C:\Users\accel\ProjectHome\phonogenesis\pyscript\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\envbin\py37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RuleFamily is not JSON serializable
